global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs: 
      - targets: ['cadvisor:8080']

  - job_name: 'device_monitoring'
    static_configs:
      - targets: ['device_monitoring:5002']